CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  openid VARCHAR(64),
  phone VARCHAR(20),
  nickname VARCHAR(64) NOT NULL DEFAULT '',
  avatar_url VARCHAR(512),
  real_name VARCHAR(64),
  id_card_hash VARCHAR(128),
  status VARCHAR(20) NOT NULL DEFAULT 'normal',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uk_users_openid ON users(openid);
CREATE UNIQUE INDEX uk_users_phone ON users(phone);

CREATE TABLE service_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(32) NOT NULL,
  name VARCHAR(64) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uk_service_categories_code ON service_categories(code);

CREATE TABLE services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id BIGINT NOT NULL,
  name VARCHAR(128) NOT NULL,
  cover_url VARCHAR(1024),
  price_cent INT NOT NULL,
  duration_min INT NOT NULL,
  description CLOB,
  tags_json CLOB,
  rating DECIMAL(2,1),
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_services_category FOREIGN KEY (category_id) REFERENCES service_categories(id)
);

CREATE INDEX idx_services_category_enabled ON services(category_id, enabled);

CREATE TABLE stores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  address VARCHAR(255) NOT NULL,
  distance_km DECIMAL(6,2),
  rating DECIMAL(2,1),
  reviews INT NOT NULL DEFAULT 0,
  hours VARCHAR(64),
  tags_json CLOB,
  cover_url VARCHAR(1024),
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_stores_enabled ON stores(enabled);

CREATE TABLE store_service_rel (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id BIGINT NOT NULL,
  service_id BIGINT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_store_service_store FOREIGN KEY (store_id) REFERENCES stores(id),
  CONSTRAINT fk_store_service_service FOREIGN KEY (service_id) REFERENCES services(id)
);

CREATE UNIQUE INDEX uk_store_service ON store_service_rel(store_id, service_id);

CREATE TABLE schedules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id BIGINT NOT NULL,
  service_id BIGINT,
  service_date DATE NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  capacity INT NOT NULL DEFAULT 1,
  booked_count INT NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'available',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_schedules_store FOREIGN KEY (store_id) REFERENCES stores(id),
  CONSTRAINT fk_schedules_service FOREIGN KEY (service_id) REFERENCES services(id),
  CONSTRAINT chk_schedules_capacity CHECK (capacity >= 0),
  CONSTRAINT chk_schedules_booked CHECK (booked_count >= 0 AND booked_count <= capacity)
);

CREATE INDEX idx_schedules_query ON schedules(store_id, service_date, status);

CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_no VARCHAR(32) NOT NULL,
  user_id BIGINT NOT NULL,
  service_id BIGINT NOT NULL,
  store_id BIGINT NOT NULL,
  schedule_id BIGINT NOT NULL,
  contact_name VARCHAR(64) NOT NULL,
  contact_phone VARCHAR(20) NOT NULL,
  price_cent INT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  pay_status VARCHAR(20) NOT NULL DEFAULT 'unpaid',
  appointment_at TIMESTAMP NOT NULL,
  cancelled_at TIMESTAMP,
  user_hidden BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_orders_service FOREIGN KEY (service_id) REFERENCES services(id),
  CONSTRAINT fk_orders_store FOREIGN KEY (store_id) REFERENCES stores(id),
  CONSTRAINT fk_orders_schedule FOREIGN KEY (schedule_id) REFERENCES schedules(id)
);

CREATE UNIQUE INDEX uk_orders_order_no ON orders(order_no);
CREATE INDEX idx_orders_user_status_created ON orders(user_id, status, created_at);

CREATE TABLE payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL,
  channel VARCHAR(20) NOT NULL,
  amount_cent INT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  transaction_no VARCHAR(128),
  paid_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES orders(id)
);

CREATE INDEX idx_payments_order ON payments(order_id);

CREATE TABLE negatives (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  order_id BIGINT NOT NULL,
  title VARCHAR(128) NOT NULL,
  type VARCHAR(20) NOT NULL DEFAULT 'original',
  image_url VARCHAR(1024) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'visible',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_negatives_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_negatives_order FOREIGN KEY (order_id) REFERENCES orders(id)
);

CREATE INDEX idx_negatives_user_order ON negatives(user_id, order_id);

