CREATE TABLE admin_operation_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_token_digest VARCHAR(128) NOT NULL,
  action VARCHAR(64) NOT NULL,
  target_type VARCHAR(64) NOT NULL,
  target_id BIGINT,
  detail_json CLOB,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_admin_operation_logs_target ON admin_operation_logs(target_type, target_id, created_at);
CREATE INDEX idx_admin_operation_logs_action ON admin_operation_logs(action, created_at);
