CREATE TABLE files (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_user_id BIGINT,
  storage_provider VARCHAR(32) NOT NULL,
  bucket VARCHAR(128) NOT NULL,
  object_key VARCHAR(512) NOT NULL,
  public_url VARCHAR(1024),
  mime_type VARCHAR(128) NOT NULL,
  size_byte BIGINT NOT NULL,
  usage VARCHAR(32) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'created',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_files_owner FOREIGN KEY (owner_user_id) REFERENCES users(id)
);

CREATE UNIQUE INDEX uk_files_object_key ON files(storage_provider, bucket, object_key);
CREATE INDEX idx_files_owner_usage ON files(owner_user_id, usage);

ALTER TABLE negatives ADD COLUMN file_id BIGINT;
ALTER TABLE negatives ADD COLUMN download_expires_at TIMESTAMP;
CREATE INDEX idx_negatives_file ON negatives(file_id);

CREATE TABLE admin_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(64) NOT NULL,
  display_name VARCHAR(64) NOT NULL,
  role VARCHAR(32) NOT NULL DEFAULT 'super_admin',
  token_digest VARCHAR(128) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'normal',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uk_admin_users_username ON admin_users(username);
CREATE UNIQUE INDEX uk_admin_users_token_digest ON admin_users(token_digest);

CREATE TABLE sms_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone VARCHAR(20) NOT NULL,
  code_hash VARCHAR(128) NOT NULL,
  scene VARCHAR(32) NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  consumed_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_sms_codes_phone_scene ON sms_codes(phone, scene, created_at);

CREATE TABLE payment_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL,
  channel VARCHAR(20) NOT NULL,
  event_type VARCHAR(32) NOT NULL,
  transaction_no VARCHAR(128) NOT NULL,
  raw_payload CLOB,
  processed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_payment_events_order FOREIGN KEY (order_id) REFERENCES orders(id)
);

CREATE UNIQUE INDEX uk_payment_events_transaction ON payment_events(channel, transaction_no, event_type);
