CREATE TABLE member_point_accounts (
  user_id BIGINT PRIMARY KEY,
  balance INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_member_point_accounts_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT chk_member_point_balance CHECK (balance >= 0)
);

CREATE TABLE member_point_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  type VARCHAR(32) NOT NULL,
  delta_points INT NOT NULL,
  balance_after INT NOT NULL,
  source VARCHAR(32) NOT NULL,
  source_order_id BIGINT,
  reason VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_member_point_transactions_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_member_point_transactions_order FOREIGN KEY (source_order_id) REFERENCES orders(id),
  CONSTRAINT chk_member_point_delta CHECK (delta_points <> 0),
  CONSTRAINT chk_member_point_after CHECK (balance_after >= 0)
);

CREATE INDEX idx_member_point_transactions_user ON member_point_transactions(user_id, created_at);
CREATE UNIQUE INDEX uk_member_point_order_type ON member_point_transactions(source_order_id, type);

CREATE TABLE member_wallet_accounts (
  user_id BIGINT PRIMARY KEY,
  balance_cent INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_member_wallet_accounts_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT chk_member_wallet_balance CHECK (balance_cent >= 0)
);

CREATE TABLE member_wallet_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  type VARCHAR(32) NOT NULL,
  delta_cent INT NOT NULL,
  balance_after_cent INT NOT NULL,
  source VARCHAR(32) NOT NULL,
  source_order_id BIGINT,
  reason VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_member_wallet_transactions_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_member_wallet_transactions_order FOREIGN KEY (source_order_id) REFERENCES orders(id),
  CONSTRAINT chk_member_wallet_delta CHECK (delta_cent <> 0),
  CONSTRAINT chk_member_wallet_after CHECK (balance_after_cent >= 0)
);

CREATE INDEX idx_member_wallet_transactions_user ON member_wallet_transactions(user_id, created_at);

CREATE TABLE member_coupons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  title VARCHAR(128) NOT NULL,
  coupon_type VARCHAR(32) NOT NULL DEFAULT 'amount',
  amount_cent INT NOT NULL,
  threshold_cent INT NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'available',
  valid_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP NOT NULL,
  used_at TIMESTAMP,
  source VARCHAR(32) NOT NULL,
  source_order_id BIGINT,
  reason VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_member_coupons_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_member_coupons_order FOREIGN KEY (source_order_id) REFERENCES orders(id),
  CONSTRAINT chk_member_coupon_amount CHECK (amount_cent > 0),
  CONSTRAINT chk_member_coupon_threshold CHECK (threshold_cent >= 0),
  CONSTRAINT chk_member_coupon_status CHECK (status IN ('available', 'used', 'voided'))
);

CREATE INDEX idx_member_coupons_user_status ON member_coupons(user_id, status, expires_at);

CREATE TABLE member_cards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  title VARCHAR(128) NOT NULL,
  applicable_service_id BIGINT,
  total_times INT NOT NULL,
  remaining_times INT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'valid',
  valid_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP,
  source VARCHAR(32) NOT NULL,
  source_order_id BIGINT,
  reason VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_member_cards_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_member_cards_service FOREIGN KEY (applicable_service_id) REFERENCES services(id),
  CONSTRAINT fk_member_cards_order FOREIGN KEY (source_order_id) REFERENCES orders(id),
  CONSTRAINT chk_member_card_total CHECK (total_times > 0),
  CONSTRAINT chk_member_card_remaining CHECK (remaining_times >= 0 AND remaining_times <= total_times),
  CONSTRAINT chk_member_card_status CHECK (status IN ('valid', 'used_up', 'voided'))
);

CREATE INDEX idx_member_cards_user_status ON member_cards(user_id, status, expires_at);

CREATE TABLE member_card_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  card_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  type VARCHAR(32) NOT NULL,
  delta_times INT NOT NULL,
  remaining_after INT NOT NULL,
  source VARCHAR(32) NOT NULL,
  reason VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_member_card_transactions_card FOREIGN KEY (card_id) REFERENCES member_cards(id),
  CONSTRAINT fk_member_card_transactions_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT chk_member_card_delta CHECK (delta_times <> 0),
  CONSTRAINT chk_member_card_after CHECK (remaining_after >= 0)
);

CREATE INDEX idx_member_card_transactions_card ON member_card_transactions(card_id, created_at);

INSERT INTO member_point_accounts(user_id, balance)
SELECT user_id, CAST(SUM(price_cent / 100) AS INT)
FROM orders
WHERE pay_status = 'paid'
GROUP BY user_id;

INSERT INTO member_point_transactions(user_id, type, delta_points, balance_after, source, source_order_id, reason)
SELECT o.user_id,
       'order_paid',
       CAST(o.price_cent / 100 AS INT),
       a.balance,
       'migration',
       o.id,
       '历史已支付订单积分补记'
FROM orders o
JOIN member_point_accounts a ON a.user_id = o.user_id
WHERE o.pay_status = 'paid';
